name       : sdl2-ttf
version    : 2.0.15
release    : 6
source     :
    - https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.15.tar.gz : a9eceb1ad88c1f1545cd7bd28e7cbc0b2c14191d40238f531a15b01b1b22cd33
license    : Zlib
component  : multimedia.library
summary    : A sample library which allows you to use TrueType fonts in SDL applications.
description: |
    A sample library which allows you to use TrueType fonts in SDL applications.
builddeps  :
    - pkgconfig32(freetype2)
    - pkgconfig32(gl)
    - pkgconfig32(sdl2)
    - pkgconfig32(xshmfence)
emul32     : yes
optimize   : speed
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
