name       : sdl2-ttf
version    : 2.0.14
release    : 3
source     :
    - https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz : 34db5e20bcf64e7071fe9ae25acaa7d72bdc4f11ab3ce59acc768ab62fe39276
license    : Zlib
summary    : A sample library which allows you to use TrueType fonts in SDL applications.
description: |
    A sample library which allows you to use TrueType fonts in SDL applications.
builddeps  :
    - pkgconfig(sdl2)
    - pkgconfig32(sdl2)
    - pkgconfig32(sdl2)
    - pkgconfig32(gl)
    - pkgconfig32(xshmfence)
    - pkgconfig32(freetype2)
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
emul32     : yes
optimize   : speed
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
