name       : sdl2-ttf
version    : 2.20.2
release    : 10
source     :
    - https://github.com/libsdl-org/SDL_ttf/archive/refs/tags/release-2.20.2.tar.gz : 0fe9d587cdc4e6754b647536d0803bea8ca6ac77146c4209e0bed22391cf8241
license    : Zlib
component  : multimedia.library
summary    : A sample library which allows you to use TrueType fonts in SDL applications.
description: |
    A sample library which allows you to use TrueType fonts in SDL applications.
builddeps  :
    - pkgconfig32(freetype2)
    - pkgconfig32(harfbuzz)
    - pkgconfig32(sdl2)
    - pkgconfig32(xshmfence)
emul32     : yes
optimize   : speed
setup      : |
    %configure --disable-static --enable-freetype-builtin=no --enable-harfbuzz-builtin=no
build      : |
    %make
install    : |
    %make_install
