name       : sdl2-ttf
version    : 2.20.0
release    : 9
source     :
    - https://github.com/libsdl-org/SDL_ttf/archive/refs/tags/release-2.20.0.tar.gz : 3b3ec3e00dcfd188f572b50daa74b1cb8f40120ab094ce3d9e289705fd178183
license    : Zlib
component  : multimedia.library
summary    : A sample library which allows you to use TrueType fonts in SDL applications.
description: |
    A sample library which allows you to use TrueType fonts in SDL applications.
builddeps  :
    - pkgconfig32(freetype2)
    - pkgconfig32(harfbuzz)
    - pkgconfig32(sdl2)
    - pkgconfig32(xshmfence)
emul32     : yes
optimize   : speed
setup      : |
    %configure --disable-static --enable-freetype-builtin=no --enable-harfbuzz-builtin=no
build      : |
    %make
install    : |
    %make_install
