name       : sdl2-ttf
version    : 2.0.14
release    : 2
source     :
    - https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz : 34db5e20bcf64e7071fe9ae25acaa7d72bdc4f11ab3ce59acc768ab62fe39276
license    : Zlib
summary    : A sample library which allows you to use TrueType fonts in SDL applications.
description: |
    A sample library which allows you to use TrueType fonts in SDL applications.
builddeps  :
    - pkgconfig(sdl2)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
